# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8110c143ea04c94986ff33b42192fb3fc2a0009ede26921ae870b31fb3d0e9261d9f4423d9975e65f6bca347579b987a147f20f106a3477809fe559d7588a1bc

test:
  secret_key_base: 2caf1948bef750abfe01539475807af44b3ceb287318a09b3a029f557fb2514d15bd75febd45756276224372f1313f0b800c282e1e97f1cb24156bb57a100e9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
